CREATE ARRAY

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,])
arr

array([1, 2, 3, 4, 5])

ARRAY OPERATIONS

In [3]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a+b)
print(a*b)

[11 22 33]
[10 40 90]


ZEROS AND ONES


In [4]:
print(np.zeros((2,3)))
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


MEAN, MAX, MIN

In [5]:
data = np.array([10,20,30,40])

print("mean:", np.mean(data))
print("max:", np.max(data))
print("min:", np.min(data))

mean: 25.0
max: 40
min: 10
